# Generated by Django 4.1.2 on 2022-12-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('year', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=20)),
                ('mileage', models.IntegerField(default=0)),
                ('cleanTitle', models.BooleanField(default=True)),
            ],
        ),
    ]
